# Generated by Django 4.2.10 on 2024-04-21 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('null', '---'), ('new', 'New booking'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected by Admin'), ('cancelled', 'Cancelled by Customer'), ('started', 'Start Service'), ('late', 'Late'), ('noshow', 'Customer No show'), ('queue', 'Queue'), ('completed', 'Completed'), ('changed', 'Changed'), ('deleted', 'Deleted')], default='new', max_length=100, null=True, verbose_name='Booking Status')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('mobilephone_country', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mobilephone', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('people', models.IntegerField(default=1)),
                ('remark', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.branch')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.member')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('enabled', models.BooleanField(default=True)),
                ('slot_total', models.IntegerField(default=1)),
                ('slot_available', models.IntegerField(default=1)),
                ('slot_using', models.IntegerField(default=0)),
                ('show_date', models.DateTimeField()),
                ('show_end_date', models.DateTimeField()),
                ('created_by_temp', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.branch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SMS_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('numSMS', models.IntegerField(default=0)),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(blank=True, default=django.db.models.deletion.SET_NULL, null=True)),
                ('return_code', models.IntegerField(blank=True, default=django.db.models.deletion.SET_NULL, null=True)),
                ('msg_for', models.CharField(blank=True, max_length=200, null=True)),
                ('errormsg', models.CharField(blank=True, max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch')),
            ],
        ),
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtext', models.TextField(blank=True, max_length=200, null=True)),
                ('action', models.CharField(choices=[('null', '---'), ('new', 'New'), ('change', 'Change'), ('cancel', 'Cancel'), ('confirm', 'Confirm'), ('reject', 'Reject'), ('noshow', 'No show'), ('complete', 'Completed'), ('delete', 'Delete')], default='null', max_length=100, verbose_name='Time Slot Action')),
                ('status', models.CharField(choices=[('null', '---'), ('new', 'New booking'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected by Admin'), ('cancelled', 'Cancelled by Customer'), ('started', 'Start Service'), ('late', 'Late'), ('noshow', 'Customer No show'), ('queue', 'Queue'), ('completed', 'Completed'), ('changed', 'Changed'), ('deleted', 'Deleted')], default='null', max_length=100, verbose_name='Booking Status')),
                ('remark', models.TextField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.booking')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.branch')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.member')),
                ('timeslot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.timeslot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.timeslot'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
