# Generated by Django 4.2.9 on 2024-01-17 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0024_alter_crmadmin_membernumber_digit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0112_alter_countertype_countermode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('slot_total', models.IntegerField(default=1)),
                ('slot_available', models.IntegerField(default=1)),
                ('show_date', models.DateTimeField()),
                ('show_end_date', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.branch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobilephone_country', models.CharField(blank=True, max_length=200, null=True)),
                ('mobilephone', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.TextField(blank=True, max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.member')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.timeslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
