# Generated by Django 4.2.13 on 2024-06-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslottemplate',
            name='items',
            field=models.ManyToManyField(blank=True, to='booking.timeslot_item'),
        ),
    ]
