# Generated by Django 4.2.9 on 2024-01-30 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_alter_crmadmin_membernumber_digit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='people',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='created_by_temp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('full', 'Full')], default='pending', max_length=100),
        ),
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobilephone_country', models.CharField(blank=True, max_length=200, null=True)),
                ('mobilephone', models.CharField(blank=True, max_length=200, null=True)),
                ('action', models.CharField(choices=[('new', 'New booking'), ('change', 'Change booking'), ('cancel', 'Cancel booking'), ('confirm', 'Confirm booking'), ('reject', 'Reject booking'), ('noshow', 'No show'), ('complete', 'Completed booking')], default='new', max_length=100)),
                ('remark', models.TextField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
