# Generated by Django 4.2.10 on 2024-05-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinglog',
            old_name='status',
            new_name='booking_status',
        ),
        migrations.RenameField(
            model_name='bookinglog',
            old_name='action',
            new_name='timeslot_action',
        ),
    ]
