# Generated by Django 4.2.10 on 2024-02-10 15:44

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(default=base.models.Branch.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
    ]
