# Generated by Django 4.2.9 on 2024-02-01 04:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_people_timeslot_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinglog',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bookinglog',
            name='mobilephone',
        ),
        migrations.RemoveField(
            model_name='bookinglog',
            name='mobilephone_country',
        ),
        migrations.RemoveField(
            model_name='bookinglog',
            name='name',
        ),
        migrations.AddField(
            model_name='bookinglog',
            name='logtext',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookinglog',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.timeslot'),
            preserve_default=False,
        ),
    ]
