# Generated by Django 4.2.10 on 2024-02-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_bookinglog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('null', 'Null'), ('new', 'New booking'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('late', 'Late'), ('noshow', 'Customer No show'), ('rejected', 'Rejected by Admin'), ('cancelled', 'Cancelled by Customer')], default='new', max_length=100, null=True, verbose_name='Booking Status'),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='status',
            field=models.CharField(choices=[('null', 'Null'), ('new', 'New booking'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('late', 'Late'), ('noshow', 'Customer No show'), ('rejected', 'Rejected by Admin'), ('cancelled', 'Cancelled by Customer')], default='null', max_length=100, verbose_name='Booking Status'),
        ),
    ]
