# Generated by Django 4.2.13 on 2024-07-13 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_countertype_branch_alter_device_branch_and_more'),
        ('booking', '0002_timeslottemplate_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_log',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
    ]
