# Generated by Django 4.2.10 on 2024-05-22 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_status_bookinglog_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglog',
            name='logtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='timeslot_action',
            field=models.CharField(choices=[('null', '---'), ('new', 'New'), ('change', 'Change'), ('delete', 'Delete')], default='null', max_length=100, verbose_name='Time Slot Action'),
        ),
    ]
