# Generated by Django 4.2.9 on 2024-02-01 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_alter_crmadmin_membernumber_digit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_remove_bookinglog_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinglog',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.member'),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.timeslot'),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
