# Generated by Django 4.2.13 on 2024-05-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookinglog_logtime_alter_bookinglog_timeslot_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='late_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='lated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('null', '---'), ('new', 'New booking'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected by Admin'), ('cancelled', 'Cancelled by Customer'), ('arrived', 'Customer Arrived'), ('noshow', 'Customer No show'), ('started', 'Start Service'), ('queue', 'Queue'), ('started_ontime', 'Start Service (force on time)'), ('queue_ontime', 'Queue (force on time)'), ('completed', 'Completed'), ('changed', 'Changed'), ('deleted', 'Deleted')], default='new', max_length=100, null=True, verbose_name='Booking Status'),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='booking_status',
            field=models.CharField(choices=[('null', '---'), ('new', 'New booking'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected by Admin'), ('cancelled', 'Cancelled by Customer'), ('arrived', 'Customer Arrived'), ('noshow', 'Customer No show'), ('started', 'Start Service'), ('queue', 'Queue'), ('started_ontime', 'Start Service (force on time)'), ('queue_ontime', 'Queue (force on time)'), ('completed', 'Completed'), ('changed', 'Changed'), ('deleted', 'Deleted')], default='null', max_length=100, verbose_name='Booking Status'),
        ),
    ]
