# Generated by Django 4.2.10 on 2024-02-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_status_alter_bookinglog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('null', '---'), ('new', 'New booking'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('late', 'Late'), ('noshow', 'Customer No show'), ('rejected', 'Rejected by Admin'), ('cancelled', 'Cancelled by Customer')], default='new', max_length=100, null=True, verbose_name='Booking Status'),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='action',
            field=models.CharField(choices=[('null', '---'), ('new', 'New'), ('change', 'Change'), ('cancel', 'Cancel'), ('confirm', 'Confirm'), ('reject', 'Reject'), ('noshow', 'No show'), ('complete', 'Completed'), ('delete', 'Delete')], default='null', max_length=100, verbose_name='Time Slot Action'),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='status',
            field=models.CharField(choices=[('null', '---'), ('new', 'New booking'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('late', 'Late'), ('noshow', 'Customer No show'), ('rejected', 'Rejected by Admin'), ('cancelled', 'Cancelled by Customer')], default='null', max_length=100, verbose_name='Booking Status'),
        ),
    ]
