# Generated by Django 4.2.10 on 2024-05-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_arrival_time_booking_late_min_booking_lated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='isubtype',
            field=models.IntegerField(default=0),
        ),
    ]
