# Generated by Django 4.2.10 on 2024-02-10 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('booking', '0004_bookinglog_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinglog',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
    ]
