# Generated by Django 4.2.10 on 2024-02-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_status_alter_bookinglog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('null', '---'), ('new', 'New booking'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected by Admin'), ('cancelled', 'Cancelled by Customer'), ('start', 'Start Service'), ('late', 'Late'), ('noshow', 'Customer No show'), ('queue', 'Queue'), ('completed', 'Completed')], default='new', max_length=100, null=True, verbose_name='Booking Status'),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='status',
            field=models.CharField(choices=[('null', '---'), ('new', 'New booking'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected by Admin'), ('cancelled', 'Cancelled by Customer'), ('start', 'Start Service'), ('late', 'Late'), ('noshow', 'Customer No show'), ('queue', 'Queue'), ('completed', 'Completed')], default='null', max_length=100, verbose_name='Booking Status'),
        ),
    ]
