# Generated by Django 4.2.8 on 2024-02-04 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0024_alter_crmadmin_membernumber_digit_and_more'),
        ('booking', '0004_alter_bookinglog_booking_alter_bookinglog_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.member'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='action',
            field=models.CharField(choices=[('new', 'New'), ('change', 'Change'), ('cancel', 'Cancel'), ('confirm', 'Confirm'), ('reject', 'Reject'), ('noshow', 'No show'), ('complete', 'Completed')], default='new', max_length=100),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
