# Generated by Django 4.2.13 on 2024-06-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_isubtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_score',
            field=models.IntegerField(default=0),
        ),
    ]
