# Generated by Django 4.2.10 on 2024-02-16 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_branch_bookingsms_branch_bookingsmsresetday_and_more'),
        ('booking', '0005_alter_bookinglog_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('ref', models.CharField(max_length=200, null=True)),
                ('status', models.IntegerField(default=django.db.models.deletion.SET_NULL, null=True)),
                ('return_code', models.IntegerField(default=django.db.models.deletion.SET_NULL, null=True)),
                ('msg_for', models.CharField(max_length=200, null=True)),
                ('errormsg', models.CharField(max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.booking')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ticket')),
                ('tickettemp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tickettemp')),
                ('timeslot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.timeslot')),
            ],
        ),
    ]
