# Generated by Django 4.2.8 on 2024-02-04 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0024_alter_crmadmin_membernumber_digit_and_more'),
        ('booking', '0005_alter_booking_member_alter_booking_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinglog',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.member'),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.timeslot'),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
