# Generated by Django 4.2.13 on 2024-06-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_booking_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='force_ontime',
            field=models.BooleanField(default=False),
        ),
    ]
