# Generated by Django 4.2.10 on 2024-02-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_sms_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms_log',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='sms_log',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='sms_log',
            name='tickettemp',
        ),
        migrations.RemoveField(
            model_name='sms_log',
            name='timeslot',
        ),
    ]
