# Generated by Django 4.2.13 on 2024-06-19 09:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_branch_bookingtoqueuerationormal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0007_booking_force_ontime'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(default='Booking Template', max_length=100)),
                ('sunday', models.BooleanField(default=False)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('show_day_before', models.FloatField(default=7, help_text='Show the booking before start_date, 7 means 7 days before')),
                ('show_period', models.FloatField(default=5, help_text='Show the booking period, 5 means 5 days')),
                ('create_before', models.FloatField(default=8, help_text='Create the booking before show_day, e.g. booking:6-30 show_day_before=7 create_before=8, then create booking at 6-15')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.branch')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('service_hours', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)])),
                ('service_mins', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(59), django.core.validators.MinValueValidator(0)])),
                ('slot_total', models.IntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.branch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TempLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bookingtemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingtemplate')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.timeslot_item')),
            ],
        ),
        migrations.AddField(
            model_name='bookingtemplate',
            name='items',
            field=models.ManyToManyField(blank=True, to='booking.timeslot_item'),
        ),
    ]
