# Generated by Django 4.2.10 on 2024-02-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_sms_log_booking_remove_sms_log_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms_log',
            name='numSMS',
            field=models.IntegerField(default=0),
        ),
    ]
