# Generated by Django 4.2.10 on 2024-02-17 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_sms_log_numsms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_log',
            name='errormsg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sms_log',
            name='msg_for',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sms_log',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sms_log',
            name='ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sms_log',
            name='return_code',
            field=models.IntegerField(blank=True, default=django.db.models.deletion.SET_NULL, null=True),
        ),
        migrations.AlterField(
            model_name='sms_log',
            name='status',
            field=models.IntegerField(blank=True, default=django.db.models.deletion.SET_NULL, null=True),
        ),
    ]
