# Generated by Django 4.2.13 on 2024-06-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_branch_bookingtoqueuerationormal'),
        ('booking', '0008_bookingtemplate_timeslot_item_templog_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingTemplate',
            new_name='TimeslotTemplate',
        ),
    ]
