# Generated by Django 4.2.13 on 2024-06-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_rename_bookingtemplate_timeslottemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot_item',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
