# Generated by Django 4.2.13 on 2024-06-21 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0010_timeslot_item_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot_item',
            name='user',
        ),
        migrations.AddField(
            model_name='timeslottemplate',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who own this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
