"""
Django settings for aqs project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
# aqs.settings.py
from pathlib import Path
from django.contrib.messages import constants as messages
from datetime import timedelta
from celery import Celery

aqs_version = '8.1.6'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9e^jTw&jk-@-^5u45=*m^el@@$$!7#gav!y=8r8e*&l64^@*v#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000 # higher than the count of fields (default 1000)

# Application definition

INSTALLED_APPS = [
    'channels',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'base.apps.BaseConfig',
    'rest_framework',
    
    'django_apscheduler',
    'captcha',
    'rest_framework_simplejwt',

]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_auto_logout.middleware.auto_logout', # Django auto logout (1)

]

ROOT_URLCONF = 'aqs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_auto_logout.context_processors.auto_logout_client', # Django auto logout (2)
            ],
        },
    },
]

# WSGI_APPLICATION = 'aqs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'aqsdb8',
#         'USER': 'aqsdbuser',
#         'PASSWORD': 'dbpassword-Dlcg1dwMOXSKIAIM',
#         'HOST': '192.168.1.4',
#         'PORT': '5432',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'Asia/Hong_Kong'
TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS =[
    BASE_DIR / 'static'
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',

    )
}

RECAPTCHA_PUBLIC_KEY = '6Lff1ZsiAAAAAESuPub5qJCSN8Fo1cmhtjd8bdB8'
RECAPTCHA_PRIVATE_KEY = '6Lff1ZsiAAAAAMbsSNu5KyIGWOxmjTOFHANffcAo'
RECAPTCHA_REQUIRED_SCORE = 0.85

AUTO_LOGOUT = {
                'IDLE_TIME': 3600, 
                'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
                }  # logout after 1 hour of downtime # Django auto logout (3)

# main.html add {{ redirect_to_login_immediately }}  # Django auto logout (4)

MESSAGE_TAGS = {
    messages.SUCCESS: 'msgsuccess',
    messages.ERROR: 'msgerror',
  }



ASGI_APPLICATION = 'aqs.asgi.application'

REDIS_HOST = '127.0.0.1'
CHANNEL_LAYERS = {
    'default':{
        'BACKEND':'channels_redis.core.RedisChannelLayer',
        # 'BACKEND':'channels_redis.pubsub.RedisPubSubChannelLayer',
        'CONFIG': {
            # 'hosts':[('127.0.0.1', '6379')],
            'hosts':[(REDIS_HOST, '6379')],      # vm
        # "channel_capacity": {
        #         "http.request": 200,
        #         "http.response!*": 10,
        #         re.compile(r"^websocket.send\!.+"): 20,
        #     },
        },
    }
}

CELERY_BROKER_URL = 'redis://' + REDIS_HOST + ':6379/0'
CELERY_RESULT_BACKEND = 'redis://' + REDIS_HOST + ':6379/0'
CELERY_TASK_LOG_LEVEL = 'DEBUG'
# set the celery timezone
CELERY_TIMEZONE = 'UTC'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,    
    'loggers': {
        'django': {
            'handlers': ['console', 'logfile'],
            'level': 'INFO',
            'propagate': True,
        },
        'aqs' : {
            'handlers': ['console_aqs', 'logfile_aqs'],
            'level': 'INFO',
        },
        'base' : {
            'handlers': ['console_base', 'logfile_base'],
            'level': 'INFO',
        },

    },
    'formatters': {
        'simple': {
            'format': '{levelname} {asctime} {module}>{funcName} {message}',
            'style': '{',
        },
        'simple_base': {
            'format': '{levelname} {asctime} base>{module}>{funcName} {message}',
            'style': '{',
        },
        'simple_aqs': {
            'format': '{levelname} {asctime} aqs>{module}>{funcName} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'logfile': {
            'class':'logging.handlers.RotatingFileHandler',
            'filename': f'{BASE_DIR}/logs/aqs.log',
            'mode': 'a',
            'encoding': 'utf-8',
            'formatter': 'simple',
            'maxBytes': 1024*1024*5, # 5 MB
        },
        'console_base': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple_base',
        },
        'logfile_base': {
            'class':'logging.handlers.RotatingFileHandler',
            'filename': f'{BASE_DIR}/logs/aqs.log',
            'mode': 'a',
            'encoding': 'utf-8',
            'formatter': 'simple_base',
            'maxBytes': 1024*1024*5, # 5 MB
        },
        'console_aqs': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple_aqs',
        },
        'logfile_aqs': {
            'class':'logging.handlers.RotatingFileHandler',
            'filename': f'{BASE_DIR}/logs/aqs.log',
            'mode': 'a',
            'encoding': 'utf-8',
            'formatter': 'simple_aqs',
            'maxBytes': 1024*1024*5, # 5 MB
        },
    },


}


SIMPLE_JWT = {
    # Debug mode set 120 minutes, otherwise 5 minutes    
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=120),
    # Debug mode set 30 minutes, otherwise days=1
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
   
    "AUTH_HEADER_TYPES": ("Bearer",),
   
}
