"""
Django settings for newproj project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
# aqs.settings.py
from pathlib import Path
from django.contrib.messages import constants as messages
from datetime import timedelta
import os
from .custom_handlers import CustomRotatingFileHandler

aqs_version = '8.3.12'
# APP_NAME for ws://localhost:8000/ws/APP_NAME/...
APP_NAME = 'aqs_app'

ADMIN_ENABLED = True
# for production disable Admin page, set ADMIN_ENABLED = False
# ADMIN_ENABLED = False
celery_name = 'celery_aqs'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9e^jTw&jk-@-^5u45=*m^el@@$$!7#gav!y=8r8e*&l64^@*v#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000 # higher than the count of fields (default 1000)

# Application definition

INSTALLED_APPS = [
    'base',
    'crm',
    'booking',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rest_framework',    
    'django_apscheduler',
    'captcha',
    'rest_framework_simplejwt',
    'channels',
    'qrcode',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_auto_logout.middleware.auto_logout', # Django auto logout (1)

]

ROOT_URLCONF = 'aqs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_auto_logout.context_processors.auto_logout_client', # Django auto logout (2)
            ],
        },
    },
]

# WSGI_APPLICATION = 'aqs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'aqsdb8',
#         'USER': 'aqsdbuser',
#         'PASSWORD': 'dbpassword-Dlcg1dwMOXSKIAIM',
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'Asia/Hong_Kong'
TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS =[
    BASE_DIR / 'static'
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',

    )
}

# Recaptcha settings
RECAPTCHA_ENABLED = False
RECAPTCHA_PUBLIC_KEY = '6Lff1ZsiAAAAAESuPub5qJCSN8Fo1cmhtjd8bdB8'
RECAPTCHA_PRIVATE_KEY = '6Lff1ZsiAAAAAMbsSNu5KyIGWOxmjTOFHANffcAo'
RECAPTCHA_REQUIRED_SCORE = 0.85

AUTO_LOGOUT = {
                'IDLE_TIME': 36000,  # logout after 10 hour of downtime (10 hours for development)
                'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
                } 

# main.html add {{ redirect_to_login_immediately }}  # Django auto logout (4)

MESSAGE_TAGS = {
    messages.SUCCESS: 'msgsuccess',
    messages.ERROR: 'msgerror',
  }



ASGI_APPLICATION = 'aqs.asgi.application'

# REDIS_HOST = '192.168.85.135'
# REDIS_HOST = '192.168.1.4'
REDIS_HOST = 'localhost'
REDIS_PORT = '6379'
CHANNEL_LAYERS = {
    'default':{
        'BACKEND':'channels_redis.core.RedisChannelLayer',
        # 'BACKEND':'channels_redis.pubsub.RedisPubSubChannelLayer',
        'CONFIG': {
            # 'hosts':[('127.0.0.1', '6379')],
            'hosts':[(REDIS_HOST, REDIS_PORT)],
        # 'channel_capacity': {
        #         'http.request': 200,
        #         'http.response!*': 10,
        #         re.compile(r'^websocket.send\!.+'): 20,
        #     },
        },
    }
}

# CELERY SETTINGS
CELERY_BROKER_URL = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
CELERY_ACCEPT_CONTENT = {'application/json'}
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_BACKEND = 'django-db'
CELERY_RESULT_EXTENDED = True
CELERY_RESULT_BACKEND = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
CELERY_TASK_LOG_LEVEL = 'DEBUG'
# set the celery timezone
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,    
    'formatters': {
        'verbose': {
            'format':  '{levelname} {asctime} {module}>{funcName} {message}',
            'style': '{',
        },
    },

    'handlers': {
        'file': {
            'level': 'INFO',  # Set to INFO to avoid logging DEBUG messages            
            'class': 'aqs.custom_handlers.CustomRotatingFileHandler',            
            'filename': os.path.join(BASE_DIR, 'logs', 'aqs.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'max_log_files': 20,  # Keep only the latest 20 log files
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',  # Set to INFO to avoid logging DEBUG messages
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },     
    },
    'root': {
        'handlers': ['file', 'console'],
        'level': 'INFO',  # Set to INFO to avoid logging DEBUG messages
    },  
}
# Ensure the log directory exists
log_dir = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(log_dir):
    os.makedirs(log_dir)

SIMPLE_JWT = {
    # Debug mode set 120 minutes, otherwise 5 minutes    
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=999),
    # Debug mode set 30 minutes, otherwise days=1
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
   
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# SMTP email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.us-east-1.awsapps.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'tim@tsvd.com.hk'
EMAIL_HOST_PASSWORD = 'happy@5345'

# SMS settings
SMS_ACCOUNT_NAME = 'tsvd@u3.ufosend.com'
SMS_API_KEY = '4a49b8f67965e61e'
SMS_SENDER = 'TSVD'