# Generated by Django 4.2.6 on 2023-11-21 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('number', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('verifycode', models.CharField(max_length=200, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('token', models.CharField(max_length=200, null=True)),
                ('tokenexpire', models.DateTimeField(blank=True, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('memberpoint', models.IntegerField(default=0)),
                ('memberpointtotal', models.IntegerField(default=0)),
                ('memberlevel', models.CharField(max_length=10, null=True)),
                ('nickname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('mobilephone', models.CharField(max_length=200, null=True)),
                ('mobilephone_country', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
