# Generated by Django 4.2.6 on 2023-11-21 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='tokenexpire',
            new_name='tokendate',
        ),
    ]
