# Generated by Django 4.2.13 on 2024-07-09 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushid', models.CharField(blank=True, max_length=200, null=True)),
                ('msgtype', models.CharField(choices=[('NEWS', 'Member news / discount'), ('Q', 'Quotation or Invoice to be confirmed')], default='news', max_length=32)),
                ('message', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('imageurl', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.company')),
            ],
        ),
    ]
