# Generated by Django 4.2.6 on 2023-11-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_tokenexpire_member_tokendate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='verifycode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
