# Generated by Django 4.2.13 on 2024-07-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_pushmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, default='192.168.1.22:8000', help_text='Domain name for the company', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pushmessage',
            name='msgtype',
            field=models.CharField(choices=[('NEWS', 'Member news / discount'), ('Q', 'Quotation or Invoice to be confirmed')], default='NEWS', max_length=32),
        ),
    ]
