# Generated by Django 4.2.13 on 2024-08-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_category_company_alter_crmadmin_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=models.CharField(default='Asia/Hong_Kong', max_length=32),
        ),
    ]
