# Generated by Django 4.2.6 on 2023-11-21 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0106_alter_branch_subend_alter_branch_substart_and_more'),
        ('crm', '0004_alter_member_address_alter_member_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch'),
        ),
    ]
