# Generated by Django 4.2.6 on 2023-11-23 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0106_alter_branch_subend_alter_branch_substart_and_more'),
        ('crm', '0005_member_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='memberpoint',
            new_name='memberpoints',
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='MemberAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('nextmembernumber', models.IntegerField(default=1)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch')),
            ],
        ),
    ]
