# Generated by Django 4.2.6 on 2023-11-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0106_alter_branch_subend_alter_branch_substart_and_more'),
        ('crm', '0006_rename_memberpoint_member_memberpoints_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('des', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(default=0)),
                ('member_points', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('soldout', 'soldout'), ('outofstock', 'outofstock'), ('reserved', 'reserved'), ('pending', 'pending')], default='active', max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch')),
            ],
        ),
    ]
