# Generated by Django 4.2.13 on 2024-08-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_customer_fax_alter_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_company',
            new_name='companyname',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='customer_company',
            new_name='customer_companyname',
        ),
    ]
