# Generated by Django 4.2.15 on 2024-08-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_customer_group_customer_information_customer_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='companyname',
            field=models.CharField(blank=True, help_text='Customer company name or individual name', max_length=200, null=True, verbose_name='Customer Company Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referby',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Refer by'),
        ),
    ]
