# Generated by Django 4.2.6 on 2023-11-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_memberitem_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('soldout', 'soldout'), ('outofstock', 'outofstock'), ('reserved', 'reserved'), ('pending', 'pending')], default='active', max_length=200),
        ),
    ]
