# Generated by Django 4.2.6 on 2023-12-01 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0106_alter_branch_subend_alter_branch_substart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0010_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('referby', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_createdby', to=settings.AUTH_USER_MODEL)),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=200, null=True)),
                ('quotation_date', models.DateTimeField(auto_now_add=True)),
                ('quotation_status', models.CharField(choices=[('free', 'When a quote is created, the status is Free'), ('approved', 'When the quote is approved internally, the status is set to Approved. The quote can be printed and sent to the customer'), ('printed', 'When a quote is printed as an external document and sent to a customer for review, the status of the quote is changed to Printed'), ('negotiating', 'Indicates that the negotiations about the selected quote are in progress. This status must be set manually'), ('accepted', 'After the customer accepts the quote, the status of the quote changes to Accepted'), ('rejected', 'Indicates that the proposed Quote has been rejected by the customer'), ('processed', 'After the customer accepts the proposal, use the option Process in the appropriate menu to create a maintenance sales order from the quote data. The status of the quote changes to Processed. All the quote lines that are linked to the quote are copied to the maintenance sales order as Part Maintenance Lines'), ('canceled', 'Indicates that the quote is cancelled. Only the quotes with the status Free, Printed or Negotiating can be cancelled'), ('lost', 'Indicates that the customer has selected another supplier. This status must be set manually. This status is applicable only for Quotes that are not generated from another object')], default='active', max_length=200)),
                ('customer_company', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('sales', models.CharField(blank=True, max_length=200, null=True)),
                ('confirm_date', models.DateTimeField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('terms', models.CharField(blank=True, max_length=200, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch')),
                ('confirm_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirm_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='branchs',
            field=models.ManyToManyField(related_name='branchs', to='base.branch'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Quotation_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.quotation')),
            ],
        ),
    ]
