# Generated by Django 4.2.15 on 2024-08-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_customer_companyname_alter_customer_referby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinformation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
