# Generated by Django 4.2.15 on 2024-08-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_customerinformation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergroup',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customersource',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
