# Generated by Django 4.2.6 on 2023-12-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0106_alter_branch_subend_alter_branch_substart_and_more'),
        ('crm', '0011_customer_quotation_product_barcode_product_branchs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='branchs',
            field=models.ManyToManyField(related_name='category_branchs', to='base.branch'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='branchs',
            field=models.ManyToManyField(related_name='supplier_branchs', to='base.branch'),
        ),
        migrations.AddField(
            model_name='type',
            name='branchs',
            field=models.ManyToManyField(related_name='type_branchs', to='base.branch'),
        ),
        migrations.AlterField(
            model_name='product',
            name='branchs',
            field=models.ManyToManyField(related_name='product_branchs', to='base.branch'),
        ),
    ]
