# Generated by Django 4.2.6 on 2023-12-01 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0107_company'),
        ('crm', '0012_category_branchs_supplier_branchs_type_branchs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='branchs',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='member',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='memberadmin',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='memberitem',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='branchs',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='branchs',
        ),
        migrations.RemoveField(
            model_name='type',
            name='branchs',
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company'),
        ),
        migrations.AddField(
            model_name='member',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company'),
        ),
        migrations.AddField(
            model_name='memberadmin',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company'),
        ),
        migrations.AddField(
            model_name='memberitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company'),
        ),
        migrations.AddField(
            model_name='type',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company'),
        ),
    ]
