# Generated by Django 4.2.13 on 2024-08-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_customergroup_name_alter_customersource_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation_item',
            name='quotation',
        ),
        migrations.AddField(
            model_name='quotation',
            name='items',
            field=models.ManyToManyField(blank=True, to='crm.quotation_item'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='major_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
