# Generated by Django 4.2.13 on 2024-08-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_remove_quotation_item_quotation_quotation_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation_item',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quotation_item',
            name='sub_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quotation_item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
