# Generated by Django 4.2.13 on 2024-08-24 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_quotation_item_cost_quotation_item_sub_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='crm.member'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
