# Generated by Django 4.2.6 on 2023-12-04 10:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_rename_type_category_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_enabled', models.BooleanField(default=True)),
                ('membernumber_next', models.IntegerField(default=1)),
                ('membernumber_digit', models.IntegerField(default=3)),
                ('membernumber_reset', models.CharField(blank=True, max_length=100, null=True)),
                ('membernumber_prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('quotation_enabled', models.BooleanField(default=True)),
                ('quotationnumber_next', models.IntegerField(default=1)),
                ('quotationnumber_digit', models.IntegerField(default=3)),
                ('quotationnumber_reset', models.CharField(blank=True, max_length=100, null=True)),
                ('quotationnumber_prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('quotation_default_terms', models.CharField(blank=True, max_length=200, null=True)),
                ('quotation_default_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('inventory_enabled', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.company')),
            ],
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='company_name',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='contact_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='person',
            new_name='supplier_company',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.company'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('soldout', 'soldout'), ('outofstock', 'outofstock'), ('reserved', 'reserved'), ('pending', 'pending')], default='active', max_length=200),
        ),
        migrations.AddField(
            model_name='memberitem',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quotation_item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation_item',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.company'),
        ),
        migrations.DeleteModel(
            name='MemberAdmin',
        ),
    ]
