# Generated by Django 4.2.13 on 2024-08-24 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0015_customer_member_product_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_q', to=settings.AUTH_USER_MODEL),
        ),
    ]
