# Generated by Django 4.2.6 on 2023-12-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_crmadmin_rename_company_name_supplier_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmadmin',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
