# Generated by Django 4.2.6 on 2023-12-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_crmadmin_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmadmin',
            name='membernumber_reset',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reset Member Number role'),
        ),
        migrations.AlterField(
            model_name='crmadmin',
            name='quotation_default_remark',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crmadmin',
            name='quotation_default_terms',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
