# Generated by Django 4.2.13 on 2024-08-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_crmadmin_membernumber_prefix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quotation_status',
            field=models.CharField(choices=[('draft', 'Draft, when a quote is created'), ('approved', 'Approved, when the quote is approved internally. The quote can be printed and sent to the customer'), ('printed', 'Printed, When a quote is printed as an external document and sent to a customer for review.'), ('negotiating', 'Indicates that the negotiations about the selected quote are in progress. This status must be set manually'), ('accepted', 'Accepted, after the customer accepts the quote.'), ('rejected', 'Rejected, indicates that the proposed Quote has been rejected by the customer'), ('processed', 'Processed, after the customer accepts the proposal, use the option Process in the appropriate menu to create a maintenance sales order from the quote data.'), ('canceled', 'Canceled, indicates that the quote is cancelled. Only the quotes with the status Free, Printed or Negotiating can be cancelled'), ('lost', 'Lost, indicates that the customer has selected another supplier. This status must be set manually.')], default='draft', max_length=200),
        ),
    ]
