# Generated by Django 4.2.13 on 2024-08-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_quotation_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
