# Generated by Django 4.2.8 on 2023-12-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_remove_category_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberitem',
            name='total_qty',
            field=models.IntegerField(default=0),
        ),
    ]
