# Generated by Django 4.2.13 on 2024-08-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_quotation_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
