# Generated by Django 4.2.8 on 2023-12-15 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_memberitem_total_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberitem',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
