# Generated by Django 4.2.8 on 2023-12-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_memberitem_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='verifycode_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberitem',
            name='discount_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='memberitem',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quotation_item',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quotation_item',
            name='sub_total',
            field=models.FloatField(default=0.0),
        ),
    ]
