# Generated by Django 4.2.13 on 2024-08-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_alter_quotation_item_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation_item',
            options={'ordering': ('index',)},
        ),
    ]
