# Generated by Django 4.2.8 on 2023-12-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_member_verified_member_verifycode_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='login',
            field=models.BooleanField(default=False),
        ),
    ]
