# Generated by Django 4.2.15 on 2024-08-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_alter_quotation_confirm_by_invoice_item_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmadmin',
            name='invoice_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='crmadmin',
            name='invoicenumber_digit',
            field=models.IntegerField(default=3, help_text='Invoice number digit, e.g. 3 is 001, 4 is 0001'),
        ),
        migrations.AddField(
            model_name='crmadmin',
            name='invoicenumber_next',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='crmadmin',
            name='invoicenumber_prefix',
            field=models.CharField(blank=True, help_text='Rules for Invoice number, &lt;TEXT&gt;Q-&lt;/TEXT&gt;&lt;Y&gt;&lt;/Y&gt;&lt;m&gt;&lt;/m&gt;&lt;d&gt;&lt;/d&gt;&lt;no&gt;&lt;/no&gt; is Year, Month, Day, Hour, Minute, Second, Number (%Y-%m-%d %H:%M:%S)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crmadmin',
            name='invoicenumber_reset',
            field=models.CharField(blank=True, help_text='Rules for reset member number, e.g. rules:&lt;Y&gt;2024&lt;/Y&gt; now is 2023-12-31, when now is 2024-01-01, reset member number to 1', max_length=100, null=True, verbose_name='Reset Invoice Number rules'),
        ),
    ]
