# Generated by Django 4.2.9 on 2024-01-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_member_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmadmin',
            name='membernumber_digit',
            field=models.IntegerField(default=3, help_text='Member number digit, e.g. 3 is 001, 4 is 0001'),
        ),
        migrations.AlterField(
            model_name='crmadmin',
            name='membernumber_prefix',
            field=models.CharField(blank=True, help_text='Rules for member number, &lt;TEXT&gt;MEM&lt;/TEXT&gt;&lt;Y&gt;&lt;/Y&gt;&lt;m&gt;&lt;/m&gt;&lt;d&gt;&lt;/d&gt;&lt;H&gt;&lt;/H&gt;&lt;M&gt;&lt;/M&gt;&lt;S&gt;&lt;/S&gt;&lt;no&gt;&lt;/no&gt; is Year, Month, Day, Hour, Minute, Second, Number (%Y-%m-%d %H:%M:%S)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crmadmin',
            name='membernumber_reset',
            field=models.CharField(blank=True, help_text='Rules for reset member number, e.g. rules:&lt;Y&gt;2024&lt;/Y&gt; now is 2023-12-31, when now is 2024-01-01, reset member number to 1', max_length=100, null=True, verbose_name='Reset Member Number rules'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('company', 'username')},
        ),
    ]
