# Generated by Django 4.2.15 on 2024-08-27 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0024_crmadmin_invoice_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmadmin',
            name='receipt_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='crmadmin',
            name='receiptnumber_digit',
            field=models.IntegerField(default=3, help_text='Receipt number digit, e.g. 3 is 001, 4 is 0001'),
        ),
        migrations.AddField(
            model_name='crmadmin',
            name='receiptnumber_next',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='crmadmin',
            name='receiptnumber_prefix',
            field=models.CharField(blank=True, help_text='Rules for receipt number, &lt;TEXT&gt;R-&lt;/TEXT&gt;&lt;Y&gt;&lt;/Y&gt;&lt;m&gt;&lt;/m&gt;&lt;d&gt;&lt;/d&gt;&lt;no&gt;&lt;/no&gt; is Year, Month, Day, Hour, Minute, Second, Number (%Y-%m-%d %H:%M:%S)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crmadmin',
            name='receiptnumber_reset',
            field=models.CharField(blank=True, help_text='Rules for reset member number, e.g. rules:&lt;Y&gt;2024&lt;/Y&gt; now is 2023-12-31, when now is 2024-01-01, reset member number to 1', max_length=100, null=True, verbose_name='Reset receipt Number rules'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(choices=[('draft', 'Draft, when a quote is created'), ('waiting', 'Invoice sent to customer, waiting for payment'), ('paid', 'Invoice paid by customer'), ('void', 'Invoice voided')], default='draft', max_length=200),
        ),
        migrations.CreateModel(
            name='Receipt_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField(default=0.0)),
                ('cost', models.FloatField(default=0.0)),
                ('sub_total', models.FloatField(default=0.0)),
                ('sub_cost', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.product')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('version', models.IntegerField(default=1)),
                ('major_version', models.IntegerField(default=1)),
                ('receipt_date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.CharField(choices=[('cheque', 'Cheque'), ('transfer', 'Bank transfer'), ('creditcard', 'Credit Card'), ('paypal', 'Paypal'), ('cash', 'Cash')], default='cheque', max_length=200)),
                ('customer_companyname', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('confirm_date', models.DateTimeField(blank=True, null=True)),
                ('total', models.FloatField(default=0.0)),
                ('cost', models.FloatField(default=0.0)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.company')),
                ('confirm_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirm_by_r', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
                ('items', models.ManyToManyField(blank=True, to='crm.receipt_item')),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_r', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
