# Generated by Django 4.2.16 on 2024-10-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_businesstype_businesssource_quotation_businesssource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('standard', 'Standard Invoice'), ('credit', 'Credit Invoice'), ('debit', 'Debit Invoice'), ('mixed', 'Mixed Invoice'), ('proforma', 'Proforma Invoice')], default='standard', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cheque', 'Cheque'), ('transfer', 'Bank transfer'), ('creditcard', 'Credit Card'), ('paypal', 'Paypal'), ('cash', 'Cash')], default='cheque', max_length=200),
        ),
    ]
