# Generated by Django 4.2.17 on 2025-02-10 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_invoice_invoice_type_invoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
