# Generated by Django 4.0.3 on 2022-05-03 09:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcode', models.CharField(max_length=200, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('gps', models.TextField(blank=True, null=True)),
                ('officehourstart', models.TimeField(default=datetime.time(9, 0))),
                ('officehourend', models.TimeField(default=datetime.time(18, 0))),
                ('tickettimestart', models.TimeField(default=datetime.time(8, 0))),
                ('tickettimeend', models.TimeField(default=datetime.time(17, 0))),
                ('ticketmax', models.IntegerField(default=999)),
                ('ticketnext', models.IntegerField(default=1)),
                ('ticketnoformat', models.TextField(default='000')),
                ('ticketrepeatnumber', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branchs')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickettype', models.CharField(blank=True, max_length=200, null=True)),
                ('staffnumber', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('branchs', models.ManyToManyField(blank=True, related_name='branchs_u', to='base.branchs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickettype', models.CharField(max_length=200)),
                ('ticketnumber', models.CharField(max_length=200)),
                ('step', models.IntegerField(default=1)),
                ('status', models.TextField(default='waiting')),
                ('tickettime', models.DateTimeField()),
                ('tickettext', models.TextField(default='')),
                ('printernumber', models.TextField(default='')),
                ('printedtimes', models.IntegerField(default=0)),
                ('remark', models.TextField(default='')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branchs')),
                ('countertype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.countertype')),
            ],
        ),
        migrations.CreateModel(
            name='TicketRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('tickettype', models.CharField(max_length=200)),
                ('step', models.IntegerField(default=1)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branchs')),
                ('countertype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.countertype')),
            ],
        ),
        migrations.CreateModel(
            name='TicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickettype', models.CharField(max_length=200)),
                ('ticketnumber', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branchs')),
            ],
        ),
        migrations.CreateModel(
            name='TicketFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('ttype', models.CharField(max_length=10)),
                ('tformat', models.TextField()),
                ('nextno', models.IntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('branchs', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branchs_t', to='base.branchs')),
            ],
            options={
                'ordering': ['branchs', 'ttype'],
            },
        ),
    ]
