# Generated by Django 4.2.10 on 2024-04-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
