# Generated by Django 4.0.3 on 2022-05-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branchs',
            new_name='Branch',
        ),
        migrations.AlterModelOptions(
            name='ticketformat',
            options={'ordering': ['branch', 'ttype']},
        ),
        migrations.RenameField(
            model_name='ticketformat',
            old_name='branchs',
            new_name='branch',
        ),
    ]
