# Generated by Django 4.2.10 on 2024-04-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterstatus',
            name='voice',
            field=models.CharField(default='[SC]', help_text='[SC] = Service Counter, [C1] = Counter one, [CASHIER] = Cashier', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tickettemp',
            name='booking_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tickettemp',
            name='booking_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
