# Generated by Django 4.2.10 on 2024-02-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bookingSMS',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='bookingSMSResetDay',
            field=models.IntegerField(default=1, help_text='SMS reset day of the month (1-28)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='bookingSMSTotal',
            field=models.IntegerField(default=500, help_text='Total no. of SMS per month'),
        ),
        migrations.AddField(
            model_name='branch',
            name='bookingSMSUsed',
            field=models.IntegerField(default=0, help_text='Total no. of SMS used'),
        ),
        migrations.AddField(
            model_name='branch',
            name='bookingSMSconfirm',
            field=models.TextField(blank=True, help_text='SMS message for booking confirmation, [[DATE]] is booking start date, [[TIME]] is booking start time. 160 characters / 70 characters (Unicode) per one SMS', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='bookingTextHTMLpage1',
            field=models.TextField(blank=True, default='多謝你預約我們的維修中心\n請帶發票在預約時間到維修中心\n地址: [[ADDR]]', help_text='Booking HTML page 1 text, [[ADDR]] is branch.address.', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='bookingenabled',
            field=models.BooleanField(default=True),
        ),
    ]
