# Generated by Django 4.2.10 on 2024-02-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_branch_bookingsms_branch_bookingsmsresetday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='bookingSMSTotal',
            new_name='SMSQuota',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='bookingSMSResetDay',
            new_name='SMSResetDay',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='bookingSMSUsed',
            new_name='SMSUsed',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='smsmsg',
            new_name='SMSmsg',
        ),
    ]
