# Generated by Django 4.2.10 on 2024-04-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_counterstatus_voice_alter_ticket_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterstatus',
            name='voice',
            field=models.CharField(blank=True, default='[SC]', help_text='[SC] = Service Counter, [C1] = Counter one, [CASHIER] = Cashier, Blank = No voice', max_length=50, null=True),
        ),
    ]
