# Generated by Django 4.0.3 on 2022-05-04 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_rename_branchs_branch_alter_ticketformat_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='countertype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.countertype'),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='logtext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tickettype',
            field=models.CharField(blank=True, default='ABCDEFGHIJKLMNOPQRSTUVWXYZ', max_length=200, null=True),
        ),
    ]
