# Generated by Django 4.2.10 on 2024-02-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_bookingsmstotal_branch_smsquota_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='enabledsms',
            new_name='SMSenabled',
        ),
    ]
