# Generated by Django 4.2.10 on 2024-04-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_counterstatus_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='after_enabled',
            field=models.BooleanField(default=False, help_text='Play sound effect After calling ticket'),
        ),
        migrations.AddField(
            model_name='branch',
            name='after_sound',
            field=models.TextField(default='[NOTIFY]'),
        ),
        migrations.AddField(
            model_name='branch',
            name='before_enabled',
            field=models.BooleanField(default=False, help_text='Play sound effect Before calling ticket'),
        ),
        migrations.AddField(
            model_name='branch',
            name='before_sound',
            field=models.TextField(default='[SUCCESS]'),
        ),
    ]
