# Generated by Django 4.0.3 on 2022-05-04 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_tickets_ticket_ticketlog_countertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketformat',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
    ]
