# Generated by Django 4.2.10 on 2024-02-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_enabledsms_branch_smsenabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='bookingTextHTMLpage1',
            new_name='bookingPage1Text',
        ),
        migrations.AddField(
            model_name='branch',
            name='bookingPage1ScrollingText',
            field=models.TextField(blank=True, default='Scrolling text 1', help_text='Booking HTML page 1 Scrolling text, [[ADDR]] is branch.address.', null=True),
        ),
    ]
