# Generated by Django 4.0.3 on 2022-05-04 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_ticketformat_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketlog',
            old_name='created',
            new_name='logtime',
        ),
        migrations.RemoveField(
            model_name='ticketlog',
            name='countertype',
        ),
        migrations.AddField(
            model_name='countertype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countertype',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='tickettime',
            field=models.DateTimeField(null=True),
        ),
    ]
