# Generated by Django 4.2.10 on 2024-04-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_branch_after_enabled_branch_after_sound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='after_sound',
            field=models.CharField(default='[NOTIFY]', max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='before_sound',
            field=models.CharField(default='[SUCCESS]', max_length=100),
        ),
    ]
