# Generated by Django 4.2.10 on 2024-05-02 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_branch_after_sound_alter_branch_before_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='after_enabled',
            field=models.BooleanField(default=False, help_text='Play effect sound After calling ticket'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='before_enabled',
            field=models.BooleanField(default=False, help_text='Play effect sound Before calling ticket'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id_end', models.CharField(max_length=200)),
                ('device_id_given', models.CharField(max_length=200)),
                ('device_type', models.CharField(choices=[('VC', 'Voice Component'), ('D', 'Display Panel'), ('PRT', 'Printer Control')], max_length=32)),
                ('device_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('device_ip_int', models.CharField(blank=True, max_length=20, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('lastactive', models.DateTimeField(blank=True, default=None, null=True)),
                ('settings', models.TextField(blank=True, default='', null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch')),
                ('countertype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.countertype')),
            ],
            options={
                'unique_together': {('device_id_end', 'device_id_given')},
            },
        ),
    ]
