# Generated by Django 4.2.10 on 2024-02-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_bookingtexthtmlpage1_branch_bookingpage1text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='SMSResetLast',
            field=models.CharField(blank=True, help_text='Last reset date of SMS', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='bookingPage2ScrollingText',
            field=models.TextField(blank=True, default='Scrolling text 2', help_text='Booking HTML page 2 Scrolling text, [[ADDR]] is branch.address.', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='bookingPage2Text',
            field=models.TextField(blank=True, default='請輸入 電郵 或 手機號碼(香港)\n我們發送確認信給你', help_text='Booking HTML page 2 text, [[ADDR]] is branch.address.', null=True),
        ),
    ]
