# Generated by Django 4.2.10 on 2024-05-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_branch_after_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='voice_volume',
            field=models.IntegerField(default=50),
        ),
    ]
