# Generated by Django 4.2.10 on 2024-02-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_branch_smsresetlast_branch_bookingpage2scrollingtext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bookingPage3Text',
            field=models.TextField(blank=True, default='你好 [[NAME]] :\n\n你的預約時間：\n[[DATE]] [[WEEK]]\n[[TIME]]\n請帶發票在預約時間到維修中心\n地址: [[ADDR]]\n如需要更改時間/取消預約請盡早打電話給我們 12345678\n\n這個訊息會發送去你的電郵或者手機短訊。\n\nTSVD', help_text='Booking success text, [[ADDR]] is branch address, [[NAME]] is customer name, [[DATE]] is booking start date, [[TIME]] is booking start time. [[WEEK]] is week.', null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='bookingPage1ScrollingText',
            field=models.TextField(blank=True, default='Scrolling text 1', help_text='Booking HTML page 1 Scrolling text, [[ADDR]] is branch address.', null=True),
        ),
    ]
