# Generated by Django 4.0.3 on 2022-05-04 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_alter_countertype_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countertype',
            options={'ordering': ['branch']},
        ),
        migrations.AlterModelOptions(
            name='ticketformat',
            options={},
        ),
        migrations.AlterField(
            model_name='countertype',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='countertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.countertype'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='printernumber',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='remark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tickettext',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ticketformat',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketroutes',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='ticketroutes',
            name='countertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.countertype'),
        ),
    ]
