# Generated by Django 4.2.10 on 2024-05-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_branch_voice_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketformat',
            old_name='from_booking',
            new_name='for_booking',
        ),
        migrations.AlterField(
            model_name='branch',
            name='voice_volume',
            field=models.IntegerField(default=50, help_text='Volume range 0-100 (0 is mute)'),
        ),
    ]
