# Generated by Django 4.2.10 on 2024-02-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_branch_bookingpage3text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='bookingSMSconfirm',
        ),
        migrations.AddField(
            model_name='branch',
            name='bookingSMSSuccess',
            field=models.TextField(blank=True, default='你的預約已經確認 - TSVD\n\n你的預約時間：\n[[DATE]]\n[[TIME]]\n地址: 彌敦道9號\n如需要更改時間/取消預約請盡早打電話給我們 12345678', help_text='SMS message for booking confirmation, [[DATE]] is booking start date, [[TIME]] is booking start time. 160 characters / 70 characters (Unicode) per one SMS', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='bookingSuccessEmailBody',
            field=models.TextField(blank=True, default='你好 [[NAME]] :\n\n你的預約時間：\n[[DATE]] [[WEEK]]\n[[TIME]]\n請帶發票在預約時間到維修中心\n地址: [[ADDR]]\n如需要更改時間/取消預約請盡早打電話給我們 12345678\n\nTSVD', help_text='Booking success email text, [[ADDR]] is branch address, [[NAME]] is customer name, [[DATE]] is booking start date, [[TIME]] is booking start time. [[WEEK]] is week.', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='bookingSuccessEmailSubject',
            field=models.TextField(blank=True, default='你的預約已經確認 - TSVD', help_text='Booking success email subject, [[ADDR]] is branch address, [[NAME]] is customer name, [[DATE]] is booking start date, [[TIME]] is booking start time. [[WEEK]] is week.', null=True),
        ),
    ]
