# Generated by Django 4.0.3 on 2022-05-04 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_alter_countertype_options_alter_ticketformat_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(null=True)),
                ('calltime', models.DateTimeField(null=True)),
                ('proceetime', models.DateTimeField(null=True)),
                ('donetime', models.DateTimeField(null=True)),
                ('misstime', models.DateTimeField(null=True)),
                ('waitingperiod', models.IntegerField(null=True)),
                ('walkingperiod', models.IntegerField(null=True)),
                ('processingperiod', models.IntegerField(null=True)),
                ('totalperiod', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('tickettype', models.CharField(max_length=200)),
                ('step', models.IntegerField(default=1)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch')),
                ('countertype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.countertype')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticketlog',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='ticketlog',
            name='ticketnumber',
        ),
        migrations.RemoveField(
            model_name='ticketlog',
            name='tickettime',
        ),
        migrations.RemoveField(
            model_name='ticketlog',
            name='tickettype',
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TicketRoutes',
        ),
        migrations.AddField(
            model_name='ticketdata',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ticket'),
        ),
        migrations.AddField(
            model_name='ticketdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
