# Generated by Django 4.2.10 on 2024-02-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_branch_bookingsmsconfirm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='bookingSMS',
            new_name='bookingSMSSuccessEnabled',
        ),
        migrations.AlterField(
            model_name='branch',
            name='bookingSMSSuccess',
            field=models.TextField(blank=True, default='你的預約已經確認 - TSVD\n\n你的預約時間：\n[[DATE]]\n[[TIME]]\n如需要更改時間/取消預約請盡早打電話給我們 12345678', help_text='SMS message for booking success, [[DATE]] is booking start date, [[TIME]] is booking start time. 160 characters / 70 characters (Unicode) per one SMS', null=True),
        ),
    ]
