# Generated by Django 4.2.10 on 2024-05-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_from_booking_ticketformat_for_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_tickettype', models.CharField(max_length=20)),
                ('ticketnext', models.IntegerField(default=1)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch')),
            ],
            options={
                'ordering': ['branch', 'booking_tickettype'],
                'unique_together': {('branch', 'booking_tickettype')},
            },
        ),
    ]
