# Generated by Django 4.2.10 on 2024-02-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_bookingsms_branch_bookingsmssuccessenabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='SMSQuota',
            field=models.IntegerField(default=500, help_text='Total no. of SMS per month', verbose_name='SMS Quota'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='SMSResetDay',
            field=models.IntegerField(default=1, help_text='SMS reset day of the month (1-28)', verbose_name='SMS Reset day'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='SMSUsed',
            field=models.IntegerField(default=0, help_text='Total no. of SMS used', verbose_name='SMS used in month'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='bookingSMSSuccess',
            field=models.TextField(blank=True, default='你的預約已經確認 - TSVD\n預約時間：\n[[DATE]]\n[[TIME]]\n如需要更改/取消預約請盡早致電 12345678', help_text='SMS text body for booking success, [[DATE]] is booking start date, [[TIME]] is booking start time. 160 characters / 70 characters (Unicode) per one SMS', null=True, verbose_name='Booking success SMS'),
        ),
    ]
