# Generated by Django 4.0.3 on 2022-05-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_ticketdata_ticketroute_remove_ticketlog_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countertype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
