# Generated by Django 4.2.13 on 2024-05-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_subticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bookingForceOnTime',
            field=models.BooleanField(default=True, help_text='If booking is late or early, force to on time to start service or queue', verbose_name='Booking force on time'),
        ),
    ]
