# Generated by Django 4.2.13 on 2024-06-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_branch_bookingforceontime'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bookingPrinterNumber',
            field=models.CharField(blank=True, default='P1', help_text='Printer number can be multiple printer, e.g. P1,P2,P3,... And BLANK is no print.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='bookingTicketDigit',
            field=models.IntegerField(default=3, help_text='Ticket number digit, e.g. =3 means A001, B049 =2 means A01, B49', verbose_name='Booking ticket digit (1 to 4 digits)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='bookingTicketFormat',
            field=models.IntegerField(default=0, help_text='0=Full format (e.g. B003A02), 1=Short1 (e.g. BA02), 2=Short2 (e.g. A02)', verbose_name='Booking ticket format'),
        ),
        migrations.DeleteModel(
            name='BookingTicket',
        ),
    ]
