# Generated by Django 4.2.10 on 2024-02-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_branch_smsquota_alter_branch_smsresetday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bookingSuccessEmailEnabled',
            field=models.BooleanField(default=True),
        ),
    ]
