# Generated by Django 4.0.3 on 2022-05-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_countertype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdata',
            name='calltime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketdata',
            name='donetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketdata',
            name='misstime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketdata',
            name='proceetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketdata',
            name='processingperiod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketdata',
            name='starttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketdata',
            name='totalperiod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketdata',
            name='waitingperiod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketdata',
            name='walkingperiod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
