# Generated by Django 4.2.13 on 2024-06-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_branch_bookingprinternumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='booking_score',
        ),
        migrations.RemoveField(
            model_name='tickettemp',
            name='booking_score',
        ),
        migrations.AlterField(
            model_name='branch',
            name='bookingToQueueOnTimeRangeEarly',
            field=models.IntegerField(default=15, verbose_name='Booking to Queue on time range early (1 to 30 minutes)'),
        ),
    ]
