# Generated by Django 4.2.10 on 2024-02-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_branch_bookingsuccessemailenabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='bookingSuccessEmailEnabled',
            field=models.BooleanField(default=True, verbose_name='Booking success email enabled'),
        ),
    ]
