# Generated by Django 4.0.3 on 2022-05-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_ticketdata_calltime_alter_ticketdata_donetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='printernumber',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='remark',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tickettext',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
