# Generated by Django 4.2.10 on 2024-03-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_branch_bookingsuccessemailenabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enabled_booking',
            field=models.BooleanField(default=True, help_text='Booking enabled'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enabled_crm',
            field=models.BooleanField(default=True, help_text='CRM enabled'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enabled_queue',
            field=models.BooleanField(default=True, help_text='Queue enabled'),
        ),
    ]
