# Generated by Django 4.2.13 on 2024-06-14 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0012_remove_ticket_booking_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booking_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tickettemp',
            name='booking_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_user_temp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketformat',
            name='tformat',
            field=models.TextField(default='<CEN>\n<LOGO>1\n<TEXT>歡迎光臨，請稍候<LINE>\n<TEXT>Welcome, please wait to be served<LINE>\n<LINE>\n<B_FONT>\n<TEXT>票 號<LINE>\n<TEXT>Ticket number<LINE>\n<D_FONT><TICKET><LINE>\n<N_FONT>\n<DATETIME><LINE>\n<QR><MYTICKET><LINE>\n<TEXT>掃描QR查看您的網上飛仔<LINE>\n<TEXT>Scan QR code for your e-ticket<LINE>\n<CUT>'),
        ),
    ]
