# Generated by Django 4.0.3 on 2022-05-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_ticket_printernumber_alter_ticket_remark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketformat',
            old_name='nextno',
            new_name='ticketnext',
        ),
    ]
