# Generated by Django 4.2.13 on 2024-06-16 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_ticket_booking_user_tickettemp_booking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bookingToQueueRatioNormal',
            field=models.IntegerField(default=3, help_text='Normal ratio for booking to queue, Default 3:1', verbose_name='Booking to Queue direction ratio [normal] (1 to 10)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='bookingToQueueRatioRev',
            field=models.IntegerField(default=1, help_text='Reverse ratio for booking to queue, Default 3:1', verbose_name='Booking to Queue direction ratio [Reverse] (1 to 10)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketnumber_disp',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='tickettype_disp',
            field=models.CharField(default='A', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickettemp',
            name='ticketnumber_disp',
            field=models.CharField(default='999', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickettemp',
            name='tickettype_disp',
            field=models.CharField(default='J', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='queuepriority',
            field=models.CharField(choices=[('time', 'By Booking ticket time'), ('time', 'By Ticket time'), ('user', 'By User priority'), ('mask', 'By Mask priority')], default='time', max_length=32),
        ),
    ]
