# Generated by Django 4.0.3 on 2022-05-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_nextno_ticketformat_ticketnext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketformat',
            old_name='ticketnext',
            new_name='nextno',
        ),
    ]
