# Generated by Django 4.2.10 on 2024-03-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_userprofile_enabled_booking_userprofile_enabled_crm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='enabled_booking',
            field=models.BooleanField(default=False, verbose_name='Booking enabled'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='enabled_crm',
            field=models.BooleanField(default=False, verbose_name='CRM enabled'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='enabled_queue',
            field=models.BooleanField(default=False, verbose_name='Queue enabled'),
        ),
    ]
