# Generated by Django 4.2.10 on 2024-03-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_userprofile_enabled_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='queueeabled',
            field=models.BooleanField(default=True, verbose_name='Enabled Queuing System'),
        ),
    ]
