# Generated by Django 4.2.13 on 2024-06-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_branch_bookingtoqueuerationormal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='queuepriority',
            field=models.CharField(choices=[('time', 'Booking ticket first then by ticket time'), ('tickettime', 'By Ticket time'), ('user', 'By User priority'), ('mask', 'By Mask priority')], default='time', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='queuepriority',
            field=models.CharField(choices=[('branch', 'By Branch'), ('time', 'Booking ticket first then by ticket time'), ('tickettime', 'By Ticket time'), ('user', 'By User priority'), ('mask', 'By Branch mask priority')], default='branch', help_text='Queue Priority', max_length=32),
        ),
    ]
