# Generated by Django 4.0.3 on 2022-05-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_nextno_ticketformat_ticketnext'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlog',
            name='app',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='version',
            field=models.TextField(blank=True, null=True),
        ),
    ]
