# Generated by Django 4.2.10 on 2024-03-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_branch_queueeabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='queueeabled',
            new_name='queueenabled',
        ),
    ]
