# Generated by Django 4.2.13 on 2024-06-25 01:35

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_branch_bookingtoqueuerationormal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterstatus',
            options={'ordering': [django.db.models.functions.comparison.Cast('counternumber', output_field=models.IntegerField())]},
        ),
    ]
