# Generated by Django 4.2.10 on 2024-03-06 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0016_rename_queueeabled_branch_queueenabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bookingNewEmailBody',
            field=models.TextField(blank=True, default='恭喜，你有新預約\n\n客人名稱：[[NAME]]\n預約時間：\n[[DATE]] [[WEEK]]\n[[TIME]]\n地址: [[ADDR]]\n客人電話：[[PHONE]]\n客人電郵：[[EMAIL]]\n\nTSVD', help_text='[[ADDR]] is branch address, [[NAME]] is customer name, [[DATE]] is booking start date, [[TIME]] is booking start time, [[WEEK]] is week, [[PHONE]] is customer phone, [[EMAIL]] is customer email.', null=True, verbose_name='Email body for New Booking'),
        ),
        migrations.AddField(
            model_name='branch',
            name='bookingNewEmailEnabled',
            field=models.BooleanField(default=True, verbose_name='Enabled New Booking email notification'),
        ),
        migrations.AddField(
            model_name='branch',
            name='bookingNewEmailSubject',
            field=models.TextField(blank=True, default='你有新預約 - TSVD', help_text='[[ADDR]] is branch address, [[NAME]] is customer name, [[DATE]] is booking start date, [[TIME]] is booking start time, [[WEEK]] is week, [[PHONE]] is customer phone, [[EMAIL]] is customer email.', null=True, verbose_name='Email subject for New Booking'),
        ),
        migrations.AddField(
            model_name='branch',
            name='bookingNewEmailUser',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='New Booking email list'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='bookingenabled',
            field=models.BooleanField(default=True, verbose_name='Enabled Booking system'),
        ),
    ]
