# Generated by Django 4.0.3 on 2022-05-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_ticketlog_app_ticketlog_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requeststr', models.TextField(blank=True, null=True)),
                ('ip', models.TextField(blank=True, null=True)),
                ('app', models.TextField(blank=True, null=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('logtime', models.DateTimeField(blank=True, null=True)),
                ('logtext', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
