# Generated by Django 4.2.10 on 2024-03-07 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0017_branch_bookingnewemailbody_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='bookingNewEmailBody',
            field=models.TextField(blank=True, default='恭喜，你有新預約\n\n客人名稱：[[NAME]]\n預約時間：\n[[DATE]] [[WEEK]]\n[[TIME]]\n地址: [[ADDR]]\n客人電話：[[PHONE]]\n客人電郵：[[EMAIL]]\n\nTSVD', help_text='[[ADDR]] is branch address, [[NAME]] is customer name, [[DATE]] is booking start date, [[TIME]] is booking start time, [[WEEK]] is week, [[PHONE]] is customer phone, [[EMAIL]] is customer email, [[BNAME]] is branch name, [[BCODE]] is branch code, [[USER]] is user first name.', null=True, verbose_name='Email body for New Booking'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='bookingNewEmailSubject',
            field=models.TextField(blank=True, default='你有新預約 - TSVD', help_text='[[ADDR]] is branch address, [[NAME]] is customer name, [[DATE]] is booking start date, [[TIME]] is booking start time, [[WEEK]] is week, [[PHONE]] is customer phone, [[EMAIL]] is customer email, [[BNAME]] is branch name, [[BCODE]] is branch code, [[USER]] is user first name.', null=True, verbose_name='Email subject for New Booking'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='bookingNewEmailUser',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='New Booking email list'),
        ),
    ]
