# Generated by Django 4.2.13 on 2024-07-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_counterstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterstatus',
            options={},
        ),
    ]
