# Generated by Django 4.2.10 on 2024-04-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_branch_bookingnewemailbody_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countertype',
            name='vert_showcounter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='countertype',
            name='vert_showlatest',
            field=models.BooleanField(default=True),
        ),
    ]
