# Generated by Django 4.2.13 on 2024-07-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_counterstatus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='domain',
            field=models.CharField(blank=True, default='http://192.168.1.22:8000', help_text='eTicket domain for QR code', max_length=200, null=True),
        ),
    ]
