# Generated by Django 4.0.3 on 2022-05-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
