# Generated by Django 4.0.3 on 2022-05-23 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0019_rename_settings_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='countertype',
            name='type',
            field=models.TextField(auto_created='asdf', default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='countertype',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='CounterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counternumber', models.CharField(max_length=200, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.TextField(default='waiting')),
                ('loged', models.BooleanField(default=False)),
                ('lastactive', models.DateTimeField(blank=True, null=True)),
                ('countertype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.countertype')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
