# Generated by Django 4.2.13 on 2024-07-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_branch_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingmodel2',
            name='des',
            field=models.TextField(blank=True, null=True),
        ),
    ]
