# Generated by Django 4.2.10 on 2024-04-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_countertype_vert_showcounter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countertype',
            name='latestpagehold',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='countertype',
            name='showcounter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='countertype',
            name='showlatest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='countertype',
            name='vert_latestpagehold',
            field=models.IntegerField(default=10),
        ),
    ]
