# Generated by Django 4.2.10 on 2024-04-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_countertype_showcounter_countertype_showlatest'),
    ]

    operations = [
        migrations.AddField(
            model_name='countertype',
            name='latestpagehold',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='countertype',
            name='vert_latestpagehold',
            field=models.IntegerField(default=10),
        ),
    ]
