# Generated by Django 4.0.3 on 2022-05-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_countertype_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countertype',
            unique_together={('branch', 'name')},
        ),
        migrations.RemoveField(
            model_name='countertype',
            name='type',
        ),
    ]
