# Generated by Django 4.2.13 on 2024-07-13 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_testingmodel2_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countertype',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='device',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='displayandvoice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='printerstatus',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='subscribeorder',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='subticket',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='ticketdata',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='ticketformat',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='ticketroute',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='tickettemp',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
        migrations.AlterField(
            model_name='webtouch',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.branch'),
        ),
    ]
