# Generated by Django 4.0.3 on 2022-05-23 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0022_alter_countertype_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counternumber', models.CharField(max_length=200, null=True)),
                ('logintime', models.DateTimeField(blank=True, null=True)),
                ('logouttime', models.DateTimeField(blank=True, null=True)),
                ('countertype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.countertype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
