# Generated by Django 4.2.13 on 2024-08-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_countertype_branch_alter_device_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='enabled_queue',
            field=models.BooleanField(default=True, verbose_name='Queue enabled'),
        ),
    ]
