# Generated by Django 4.0.3 on 2022-05-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_counterloginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterstatus',
            name='logintime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
