# Generated by Django 4.2.13 on 2024-08-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_company_timezone'),
        ('base', '0023_alter_userprofile_enabled_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ManyToManyField(blank=True, help_text='For CRM', related_name='company_u', to='crm.company', verbose_name='Company'),
        ),
    ]
