# Generated by Django 4.2.13 on 2024-12-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_scheduledjob_startupflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupflag',
            name='worker',
            field=models.IntegerField(default=0),
        ),
    ]
