# Generated by Django 4.0.3 on 2022-05-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_counterstatus_logintime'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='timezone',
            field=models.IntegerField(default=8),
        ),
    ]
