# Generated by Django 4.2.13 on 2024-08-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_company_timezone'),
        ('base', '0024_userprofile_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.OneToOneField(blank=True, help_text='For CRM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_u', to='crm.company', verbose_name='Company'),
        ),
    ]
