# Generated by Django 4.0.3 on 2022-05-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_setting_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='timezone',
        ),
        migrations.AddField(
            model_name='branch',
            name='timezone',
            field=models.IntegerField(default=8),
        ),
    ]
