# Generated by Django 4.2.13 on 2024-12-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_startupflag_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupflag',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='startupflag',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
