# Generated by Django 4.2.13 on 2024-12-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_rename_timestamp_startupflag_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledJob',
        ),
    ]
