# Generated by Django 4.2.13 on 2024-08-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_userprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='index_i',
            field=models.IntegerField(default=0, verbose_name='Invoice index'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='index_q',
            field=models.IntegerField(default=0, verbose_name='Queue index'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='index_r',
            field=models.IntegerField(default=0, verbose_name='Receipt index'),
        ),
    ]
