# Generated by Django 4.0.3 on 2022-05-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_printerstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerstatus',
            name='printernumber',
            field=models.TextField(blank=True, null=True),
        ),
    ]
