# Generated by Django 4.0.3 on 2022-05-30 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_printerstatus_printernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerstatus',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='printerstatus',
            unique_together={('branch', 'printernumber')},
        ),
    ]
