# Generated by Django 4.2.16 on 2024-09-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='logo',
            field=models.CharField(default='images/logo-q.svg', max_length=200),
        ),
        migrations.AlterField(
            model_name='domain',
            name='title',
            field=models.CharField(default='Auto Queuing System - TSVD', max_length=200),
        ),
    ]
