# Generated by Django 4.0.3 on 2022-05-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_printerstatus_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='status',
            field=models.CharField(choices=[('available', 'Available to borrow'), ('borrowed', 'Borrowed by someone'), ('archived', 'Archived - not available anymore')], default='available', max_length=32),
        ),
    ]
