# Generated by Django 4.2.15 on 2024-10-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_domain_logo_alter_domain_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='css',
            field=models.CharField(default='styles/style.css', max_length=200),
        ),
    ]
