# Generated by Django 4.0.3 on 2022-05-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_branch_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='status',
        ),
        migrations.AddField(
            model_name='branch',
            name='QueuePriority',
            field=models.CharField(choices=[('time', 'By Ticket time'), ('user', 'By user priority'), ('mask', 'By Mask priority')], default='time', max_length=32),
        ),
        migrations.AddField(
            model_name='branch',
            name='queuemask',
            field=models.TextField(default='CBA'),
        ),
    ]
