# Generated by Django 4.0.3 on 2022-05-31 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_remove_branch_status_branch_queuepriority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='QueuePriority',
            new_name='queuepriority',
        ),
    ]
