# Generated by Django 4.0.3 on 2022-05-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_rename_queuepriority_branch_queuepriority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='queuemask',
            field=models.CharField(blank=True, default='EDCBA', max_length=200, null=True),
        ),
    ]
