# Generated by Django 4.2.17 on 2024-12-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_startupflag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledJob',
        ),
        migrations.RenameField(
            model_name='startupflag',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='startupflag',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='startupflag',
            name='worker',
            field=models.IntegerField(default=0),
        ),
    ]
