# Generated by Django 4.0.3 on 2022-05-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_branch_queuemask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='queuemask',
            field=models.CharField(default='EDCBA', max_length=200),
        ),
    ]
