# Generated by Django 5.1.6 on 2025-03-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_delete_scheduledjob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='webtvcsslink',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='webtvlogolink',
        ),
        migrations.AddField(
            model_name='domain',
            name='eticketlink',
            field=models.CharField(blank=True, default='http://127.0.0.1:8000', help_text='eTicket link for QR code e.g. http://127.0.0.1:8000', max_length=200, null=True, verbose_name='e-Ticket link'),
        ),
        migrations.AddField(
            model_name='domain',
            name='webtvcsslink',
            field=models.TextField(default='styles/styletv.css', help_text='Default: styles/styletv.css', verbose_name='Web TV / My e-Ticket CSS'),
        ),
        migrations.AddField(
            model_name='domain',
            name='webtvlogolink',
            field=models.TextField(default='images/logo-q.svg', help_text='Default: images/logo-q.svg', verbose_name='Web TV / My e-Ticket logo'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='css',
            field=models.CharField(default='styles/style.css', help_text='Path [static]/styles/', max_length=200),
        ),
        migrations.AlterField(
            model_name='domain',
            name='logo',
            field=models.CharField(default='images/logo-q.svg', help_text='Path [static]/images/ default images/logo-q.svg', max_length=200),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(default='127.0.0.1:8000', help_text='e.g. test.tsvd.com.hk', max_length=200, unique=True, verbose_name='Domain name'),
        ),
    ]
