# Generated by Django 5.1.6 on 2025-03-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_remove_branch_domain_remove_branch_webtvcsslink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='css',
            field=models.CharField(default='styles/style.css', help_text='Path [static]/styles/ default styles/style.css', max_length=200),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(default='127.0.0.1', help_text='Default: 127.0.0.1 e.g. test.tsvd.com.hk', max_length=200, unique=True, verbose_name='Domain name'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='title',
            field=models.CharField(default='Auto Queuing System - TSVD', help_text='Default: Auto Queuing System - TSVD', max_length=200),
        ),
    ]
