# Generated by Django 4.0.3 on 2022-06-04 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_branch_queuemask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketdata',
            old_name='proceetime',
            new_name='processtime',
        ),
        migrations.RenameField(
            model_name='ticketdata',
            old_name='user',
            new_name='startuser',
        ),
        migrations.AddField(
            model_name='ticketdata',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch'),
        ),
        migrations.AddField(
            model_name='ticketdata',
            name='countertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.countertype'),
        ),
    ]
