# Generated by Django 4.0.3 on 2022-06-04 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0035_rename_proceetime_ticketdata_processtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdata',
            name='calluser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calluser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketdata',
            name='startuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
