# Generated by Django 4.0.3 on 2022-06-04 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0036_ticketdata_calluser_alter_ticketdata_startuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdata',
            name='doneuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doneuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketdata',
            name='missuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketdata',
            name='processuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
