# Generated by Django 4.0.3 on 2022-06-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_ticketdata_doneuser_ticketdata_missuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='queuepriority',
            field=models.CharField(choices=[('branch', 'By Branch'), ('time', 'By Ticket time'), ('user', 'By User priority'), ('mask', 'By Mask priority')], default='branch', max_length=32),
        ),
        migrations.AlterField(
            model_name='branch',
            name='queuepriority',
            field=models.CharField(choices=[('time', 'By Ticket time'), ('user', 'By User priority'), ('mask', 'By Mask priority')], default='time', max_length=32),
        ),
    ]
