# Generated by Django 4.0.3 on 2022-06-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_userprofile_queuepriority_alter_branch_queuepriority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='queuemask',
            field=models.CharField(default='ABCDEFGHIJKLMNOPQRSTUVWXYZ', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='queuepriority',
            field=models.CharField(choices=[('branch', 'By Branch'), ('time', 'By Ticket time'), ('user', 'By User priority'), ('mask', 'By Branch mask priority')], default='branch', max_length=32),
        ),
    ]
