# Generated by Django 4.0.3 on 2022-06-10 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0039_alter_branch_queuemask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdata',
            name='voidtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketdata',
            name='voiduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voiduser', to=settings.AUTH_USER_MODEL),
        ),
    ]
