# Generated by Django 4.0.3 on 2022-06-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_ticketdata_voidtime_ticketdata_voiduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
