# Generated by Django 4.0.3 on 2022-06-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_displaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaylist',
            name='flashtime',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='displaylist',
            name='wait',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
