# Generated by Django 4.0.3 on 2022-06-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_displaylist_flashtime_displaylist_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='displayflashtime',
            field=models.IntegerField(default=3),
        ),
    ]
