# Generated by Django 4.0.3 on 2022-06-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_branch_displayflashtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displaylist',
            options={'ordering': ['calltime']},
        ),
        migrations.AddField(
            model_name='displaylist',
            name='calltime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
