# Generated by Django 4.0.3 on 2022-06-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_alter_displaylist_options_displaylist_calltime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displaylist',
            name='updated',
        ),
    ]
