# Generated by Django 4.0.3 on 2022-06-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_remove_displaylist_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displaylist',
            options={'ordering': ['displaytime']},
        ),
        migrations.RenameField(
            model_name='displaylist',
            old_name='calltime',
            new_name='displaytime',
        ),
    ]
