# Generated by Django 4.0.3 on 2022-06-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_displaylist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countertype',
            name='displayscrollingtext',
            field=models.TextField(default='Testing 123...'),
        ),
    ]
