# Generated by Django 4.0.3 on 2022-06-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_countertype_displayscrollingtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketformat',
            name='waiting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='ticketformat',
            unique_together={('ttype', 'branch')},
        ),
    ]
