# Generated by Django 4.0.3 on 2022-06-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_ticketformat_waiting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketformat',
            name='waiting',
        ),
        migrations.AddField(
            model_name='ticketroute',
            name='waiting',
            field=models.IntegerField(default=0),
        ),
    ]
