# Generated by Django 4.0.3 on 2022-06-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_remove_ticketformat_waiting_ticketroute_waiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='language1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='language2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='language3',
            field=models.BooleanField(default=False),
        ),
    ]
