# Generated by Django 4.0.3 on 2022-06-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_branch_language1_branch_language2_branch_language3'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='language4',
            field=models.BooleanField(default=False),
        ),
    ]
