# Generated by Django 4.0.3 on 2022-06-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_branch_language4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='language1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='branch',
            name='language2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branch',
            name='language3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branch',
            name='language4',
            field=models.IntegerField(default=0),
        ),
    ]
