# Generated by Django 4.0.3 on 2022-06-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_alter_branch_language1_alter_branch_language2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='displayenabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='voiceenabled',
            field=models.BooleanField(default=True),
        ),
    ]
