# Generated by Django 4.0.3 on 2022-06-24 09:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0054_branch_displayenabled_branch_voiceenabled'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisplayList',
            new_name='DisplayAndVoice',
        ),
    ]
