# Generated by Django 4.0.3 on 2022-07-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_rename_displaylist_displayandvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketroute',
            name='displastcounter',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ticketroute',
            name='displastticket',
            field=models.CharField(default='', max_length=200),
        ),
    ]
