# Generated by Django 4.0.3 on 2022-07-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_ticketroute_displastcounter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketroute',
            old_name='displastticket',
            new_name='displastticketnumber',
        ),
        migrations.AddField(
            model_name='ticketroute',
            name='displasttickettype',
            field=models.CharField(default='', max_length=200),
        ),
    ]
