# Generated by Django 4.0.3 on 2022-07-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_rename_displastticket_ticketroute_displastticketnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='timezone',
            field=models.CharField(default='Asia/Hong_Kong', max_length=32),
        ),
    ]
