# Generated by Django 4.0.3 on 2022-07-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_alter_branch_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdata',
            name='step',
            field=models.IntegerField(default=1),
        ),
    ]
