# Generated by Django 4.0.6 on 2022-07-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_ticketdata_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketformat',
            name='tformat',
            field=models.TextField(default='<CEN>\n<LOGO>\n<TEXT>歡迎光臨，請稍候<LINE>\n<TEXT>Welcome, please wait to be served<LINE>\n<LINE>\n<B_FONT>\n<TEXT>票 號<LINE>\n<TEXT>Ticket number<LINE>\n<D_FONT><TICKET><LINE>\n<N_FONT>\n<DATETIME>\n<CUT>'),
        ),
    ]
