# Generated by Django 4.0.6 on 2022-08-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_rename_testing_testingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingmodel',
            name='des',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testingmodel',
            name='name',
            field=models.TextField(),
        ),
    ]
