# Generated by Django 4.0.6 on 2022-08-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_alter_testingmodel_des_alter_testingmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingmodel',
            name='des',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testingmodel',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
