# Generated by Django 4.1 on 2022-08-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_alter_testingmodel_des_alter_testingmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtime', models.DateTimeField(blank=True, null=True)),
                ('logtext', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ticketroute',
            name='displastcounter',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='ticketroute',
            name='displastticketnumber',
            field=models.CharField(default='---', max_length=200),
        ),
        migrations.AlterField(
            model_name='ticketroute',
            name='displasttickettype',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
