# Generated by Django 4.1 on 2022-10-17 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0066_alter_ticketroute_displastcounter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickettype', models.CharField(max_length=200)),
                ('ticketnumber', models.CharField(max_length=200)),
                ('step', models.IntegerField(default=1)),
                ('status', models.TextField(default='waiting')),
                ('locked', models.BooleanField(default=False)),
                ('tickettime', models.DateTimeField()),
                ('tickettext', models.TextField(blank=True, default='', null=True)),
                ('printernumber', models.TextField(blank=True, default='', null=True)),
                ('printedtimes', models.IntegerField(default=0)),
                ('remark', models.TextField(blank=True, default='', null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch')),
                ('countertype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.countertype')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
