# Generated by Django 4.1 on 2022-10-17 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_tickettemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdata',
            name='tickettemp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tickettemp'),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='tickettemp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tickettemp'),
        ),
    ]
