# Generated by Django 4.1 on 2022-10-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_ticketdata_tickettemp_ticketlog_tickettemp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketArchive',
        ),
    ]
