# Generated by Django 4.1 on 2022-10-18 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_delete_ticketarchive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterstatus',
            name='ticket',
        ),
        migrations.AddField(
            model_name='counterstatus',
            name='tickettemp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tickettemp'),
        ),
    ]
