# Generated by Django 4.1.2 on 2022-10-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_remove_displayandvoice_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='usersinglelogin',
            field=models.BooleanField(default=False),
        ),
    ]
