# Generated by Django 4.1.4 on 2022-12-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_branch_usersinglelogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='webtvlogolink',
            field=models.TextField(default='images/ts-logo.png'),
        ),
    ]
