# Generated by Django 4.1.4 on 2023-01-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_branch_webtvlogolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='countertype',
            name='lang1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='countertype',
            name='lang2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
