# Generated by Django 4.1.4 on 2023-01-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_countertype_lang1_countertype_lang2'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerstatus',
            name='statustext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
