# Generated by Django 4.1.4 on 2023-01-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_printerstatus_statustext'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettemp',
            name='securitycode',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='webtvlogolink',
            field=models.TextField(default='images/logo_ts.png'),
        ),
    ]
