# Generated by Django 4.1.5 on 2023-01-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_tickettemp_securitycode_alter_branch_webtvlogolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettemp',
            name='myticketlink',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
