# Generated by Django 4.1.5 on 2023-01-26 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0077_tickettemp_myticketlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettemp',
            name='createdby',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby', to=settings.AUTH_USER_MODEL),
        ),
    ]
