# Generated by Django 4.1.5 on 2023-01-26 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0081_alter_ticket_createdby_alter_tickettemp_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettemp',
            name='createdby',
            field=models.OneToOneField(blank=True, default='userapi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdbytemp', to=settings.AUTH_USER_MODEL),
        ),
    ]
