# Generated by Django 4.1.5 on 2023-01-26 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_alter_ticket_createdby_alter_tickettemp_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketformat',
            name='touchkey_lang1',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticketformat',
            name='touchkey_lang2',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticketformat',
            name='touchkey_lang3',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticketformat',
            name='touchkey_lang4',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='WebTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch')),
                ('touchkey', models.ManyToManyField(to='base.ticketformat')),
            ],
            options={
                'unique_together': {('name', 'branch')},
            },
        ),
    ]
