# Generated by Django 4.1.5 on 2023-01-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_ticketformat_touchkey_lang1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketformat',
            name='touchkey_lang1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketformat',
            name='touchkey_lang2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketformat',
            name='touchkey_lang3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketformat',
            name='touchkey_lang4',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
