# Generated by Django 4.1.7 on 2023-03-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0086_alter_ticketformat_touchkey_lang1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketformat',
            name='waiting',
            field=models.IntegerField(default=0),
        ),
    ]
