# Generated by Django 4.1.7 on 2023-03-10 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_ticketformat_waiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displayandvoice',
            name='wait',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketroute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ticketroute'),
        ),
        migrations.AddField(
            model_name='tickettemp',
            name='ticketroute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ticketroute'),
        ),
    ]
