# Generated by Django 4.1.7 on 2023-03-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_remove_displayandvoice_wait_ticket_ticketroute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketformat',
            name='waiting',
        ),
    ]
