# Generated by Django 4.1.7 on 2023-03-15 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0089_remove_ticketformat_waiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='countertype',
            name='lang3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='countertype',
            name='lang4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketformat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ticketformat'),
        ),
        migrations.AddField(
            model_name='tickettemp',
            name='ticketformat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ticketformat'),
        ),
    ]
