# Generated by Django 4.1.7 on 2023-03-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0090_countertype_lang3_countertype_lang4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='webtvcsslink',
            field=models.TextField(default='styles/styletv.css'),
        ),
    ]
