# Generated by Django 4.1.7 on 2023-03-23 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0091_branch_webtvcsslink'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='subend',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='substart',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketformat',
            name='tformat',
            field=models.TextField(default='<CEN>\n<LOGO>1\n<TEXT>歡迎光臨，請稍候<LINE>\n<TEXT>Welcome, please wait to be served<LINE>\n<LINE>\n<B_FONT>\n<TEXT>票 號<LINE>\n<TEXT>Ticket number<LINE>\n<D_FONT><TICKET><LINE>\n<N_FONT>\n<DATETIME><LINE>\n<QR>http://192.168.1.22:8000<MYTICKET><LINE>\n<TEXT>掃描QR查看您的網上飛仔<LINE>\n<TEXT>Scan QR code for your e-ticket<LINE>\n<CUT>'),
        ),
        migrations.AlterField(
            model_name='ticketroute',
            name='displastcounter',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='ticketroute',
            name='displastticketnumber',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='ticketroute',
            name='displasttickettype',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.CreateModel(
            name='SubscribeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('invoice', models.CharField(max_length=200, null=True)),
                ('remark', models.CharField(max_length=1000, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
