# Generated by Django 4.1.7 on 2023-04-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0092_branch_subend_branch_subscribe_branch_substart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobilephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
