# Generated by Django 4.1.7 on 2023-04-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0093_userprofile_mobilephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='enabledsms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='smsmsg',
            field=models.TextField(blank=True, max_length=70, null=True),
        ),
    ]
