# Generated by Django 4.1.7 on 2023-04-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0095_log_alter_branch_enabledsms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
