# Generated by Django 4.1.7 on 2023-05-20 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0096_delete_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketroute',
            options={'ordering': ['branch', 'tickettype', 'step']},
        ),
        migrations.AddField(
            model_name='countertype',
            name='countermode',
            field=models.CharField(default='normal', max_length=200),
        ),
        migrations.AddField(
            model_name='countertype',
            name='nextcounter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branch',
            name='queuemask',
            field=models.CharField(default='A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branchs',
            field=models.ManyToManyField(blank=True, help_text='Branch access rights', related_name='branchs_u', to='base.branch'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobilephone',
            field=models.CharField(blank=True, help_text='Mobile phone', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='queuepriority',
            field=models.CharField(choices=[('branch', 'By Branch'), ('time', 'By Ticket time'), ('user', 'By User priority'), ('mask', 'By Branch mask priority')], default='branch', help_text='Queue Priority', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='staffnumber',
            field=models.CharField(blank=True, default='', help_text='Staff number', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tickettype',
            field=models.CharField(blank=True, default='A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,', help_text='Ticket type', max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ticketroute',
            unique_together={('branch', 'tickettype', 'step')},
        ),
        migrations.CreateModel(
            name='UserStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(default='waiting')),
                ('logintime', models.DateTimeField(blank=True, null=True)),
                ('logouttime', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
