# Generated by Django 4.1.7 on 2023-05-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0097_alter_ticketroute_options_countertype_countermode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatuslog',
            old_name='logintime',
            new_name='endtime',
        ),
        migrations.RenameField(
            model_name='userstatuslog',
            old_name='logouttime',
            new_name='starttime',
        ),
    ]
