# Generated by Django 4.1.7 on 2023-05-21 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_rename_logintime_userstatuslog_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatuslog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstatuslog',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
