# Generated by Django 4.1.7 on 2023-05-23 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_userstatuslog_created_userstatuslog_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatuslog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ticket'),
        ),
    ]
