# Generated by Django 4.2.1 on 2023-06-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0100_userstatuslog_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='queuemask',
            field=models.CharField(default='A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,', max_length=500),
        ),
    ]
