# Generated by Django 4.1.9 on 2023-06-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0102_alter_branch_queuemask'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='flashlighttime',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='counterstatus',
            name='flashid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tickettype',
            field=models.CharField(blank=True, default='', help_text='Ticket type', max_length=200, null=True),
        ),
    ]
