# Generated by Django 4.1.9 on 2023-07-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0103_branch_flashlighttime_counterstatus_flashid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayandvoice',
            name='flashtime',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
