# Generated by Django 4.2.6 on 2023-11-21 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0105_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='subend',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='branch',
            name='substart',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
