# Generated by Django 4.2.6 on 2023-12-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0106_alter_branch_subend_alter_branch_substart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('branchs', models.ManyToManyField(blank=True, help_text='Branch access rights', related_name='branchs', to='base.branch')),
            ],
        ),
    ]
