# Generated by Django 4.2.6 on 2023-12-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0107_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
