# Generated by Django 4.2.6 on 2023-12-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0108_company_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='branchs',
        ),
    ]
