# Generated by Django 4.2.6 on 2023-12-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_rename_type_category_product_type_and_more'),
        ('base', '0109_remove_company_branchs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
