# Generated by Django 4.2.6 on 2023-12-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0110_delete_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countertype',
            name='lang1',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='countertype',
            name='lang2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='countertype',
            name='lang3',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='countertype',
            name='lang4',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
