# Generated by Django 4.2.8 on 2023-12-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0111_alter_countertype_lang1_alter_countertype_lang2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countertype',
            name='countermode',
            field=models.CharField(default='normal', help_text='Normal mode=normal, Call Centre mode=cc, Restaurant mode=res', max_length=200, verbose_name='Counter Mode'),
        ),
        migrations.AlterField(
            model_name='countertype',
            name='displayscrollingtext',
            field=models.TextField(blank=True, default='Testing 123...', null=True),
        ),
    ]
