# Generated by Django 4.2.9 on 2024-01-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0112_alter_countertype_countermode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='websoftkey_show_waitinglist',
            field=models.BooleanField(default=True),
        ),
    ]
